### ISSUE TITLE
Document deprecation rules

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_docs#124]
The developer documentation needs to define how to deprecate the following:
- APIs
- Microservices
- Rule Engine Plugins
- icommands

For example, the following rules are from https://github.com/irods/irods_client_icommands/pull/274#discussion_r812277208 and define how to deprecate an option for an icommand.
- Remove references to deprecated options from help text
- Server should add deprecation message to rError object
- Server should log deprecation message
- Update documentation to include modern way of accomplishing what is now deprecated

Related to #20

**Comment by alanking** [comment]
We discussed this a bit more in light of a slew of new deprecations and landed on an updated set of rules:

- Update documentation to include modern way of accomplishing what is now deprecated
- Add deprecation notice to help text (iCommands help, Doxygen, etc.)
- Add "deprecated" attribute to C/C++ public declarations (e.g. function, struct, typedef, ...)

Additionally, we have decided the following:
 - Server should NOT add deprecation message to rError object
 - Server should NOT log deprecation message

This is to minimize client-side / rule side effects.

**Comment by alanking** [comment]
Initial page for deprecation rules will be included in the next docs release. Please open a new issue with specific suggestions for improvements.
