### ISSUE TITLE
Add section to Troubleshooting about TCP connection timeouts

### ISSUE THREAD

**Issue by alanking** [irods/irods_docs#144]
When a client process goes away without disconnecting from the server, the connection will eventually time out and get cleaned up by the OS and handled appropriately in the server. This timeout is configurable in the kernel's TCP settings. We should add a section to Troubleshooting to describe this situation and how to change the setting. We cannot make a recommendation about what to set this value to as we will not know the needs for a given deployment.

**Comment by korydraughn** [comment]
Is this still necessary?

**Comment by trel** [comment]
It should no longer be necessary - but we still need a section in the docs that talks about it... somewhere... if we don't already have a home for that information.   These are the new options that @alanking has exposed... right?

**Comment by korydraughn** [comment]
Yes, they are.

@alanking I thought you already added a section that covers this?

**Comment by alanking** [comment]
Hmm... yes, it seems that this has been covered by https://github.com/irods/irods_docs/commit/d82772376e163f311c5d43c6cdc8eb70779fe177 / irods/irods#3986

**Comment by alanking** [comment]
I will close if we are all in agreement.

**Comment by korydraughn** [comment]
Excellent. Looks good to me.

Please close.
