### ISSUE TITLE
Changing the rodsadmin account on a consumer-side system

### ISSUE THREAD

**Issue by andrew-irods** [irods/irods_docs#17]
In a distributed iRODS setup, with one provider system, and one or more consumer systems, it is possible to use the **ipasswd** utility to change a password while being logged in to a consumer system.

If the ipasswd utility is used to change the password for the **rodsadmin** account that is ‘running’ the server (on most systems this may be the default "rods" rodsadmin account associated with the user-id "irods") while logged into a consumer system, the password will be changed successfully, however within a few seconds the iRODS server on the provider system will start showing authentication errors on the provider system every 30 seconds (see the active rodsLog log file in the ./log directory.

The iRODS server uses this rodsadmin account for houskeeping purposes every 30 seconds (i.e. database lookup of delayed execution tasks), and if the password is changed on a consumer system, the provider system will not be updated with the change, and this disrupts the operation of the server on the provider system.

In order to resolve the issue, the "iinit" command must be used to update the provider system immediately after the password is changed on any consumer system. 

**Related**

Similarly, the **iadmin** utility, when used to change the password of the *rodsadmin* account, will cause errors to occur on the iRODS server (on the provider system) every 30 seconds - regardless of whether it is run on a consumer or provider system - until the **iinit** utility is run on the provider system for the rodsadmin account.  

**Additional Troubleshooting:**

This is what the rodsLog entry looks like (2 lines per occurence) every 30 seconds:

~~~
May 22 18:32:52 pid:17897 NOTICE: rsAuthCheck: chlCheckAuth status = -826000
May 22 18:32:52 pid:17897 remote addresses: 127.0.0.1 ERROR: [-]        /home/andrew/github/irods/server/api/src/rsAuthResponse.cpp:75:int rsAuthResponse(rsComm_t *, authResponseInp_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [rcAuthCheck failed.]
       [-]     /home/andrew/github/irods/plugins/auth/native/libnative.cpp:558:irods::error native_auth_agent_response(irods::plugin_context &, authResponseInp_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [rcAuthCheck failed.]

May 22 18:33:22 pid:17904 NOTICE: rsAuthCheck: chlCheckAuth status = -826000
May 22 18:33:22 pid:17904 remote addresses: 127.0.0.1 ERROR: [-]        /home/andrew/github/irods/server/api/src/rsAuthResponse.cpp:75:int rsAuthResponse(rsComm_t *, authResponseInp_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [rcAuthCheck failed.]
       [-]     /home/andrew/github/irods/plugins/auth/native/libnative.cpp:558:irods::error native_auth_agent_response(irods::plugin_context &, authResponseInp_t *) :  status [CAT_INVALID_AUTHENTICATION]  errno [] -- message [rcAuthCheck failed.]
~~~

**Comment by alanking** [comment]
Related: https://github.com/irods/irods/issues/6136

I think this may now be covered by this commit: https://github.com/irods/irods_docs/commit/93e38caf538eec0a46a4fc73f95eb0158af0ecea

**Comment by korydraughn** [comment]
Agreed.

Closing.
