### ISSUE TITLE
Allow build container to accept Makefile parameters

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_docs#175]
This would allow developers to build the builder image one time and then generate documentation for different github accounts and commits at any time.

This removes the need for developers to modify the Makefile.

**Comment by alanking** [comment]
Do we need to cherry-pick to 4-2-stable?

**Comment by korydraughn** [comment]
I don't think so. The 4-2-stable branch is in its final stretch and I don't feel we need to devote time to porting these features to it.

Thoughts?

**Comment by trel** [comment]
Yes, let's leave 4-2-stable docs machinery as is - we'll just update the .md that gets shipped with any additional 4.2.x releases.

**Comment by alanking** [comment]
Sounds good
