### ISSUE TITLE
Update documentation for PAM authentication

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_docs#186]
The 4.3.0 documentation for PAM is not in sync with the current requirements. For example, it still references the old auth scheme value, `"PAM"`.

**Comment by alanking** [comment]
Partially remedied by this commit: https://github.com/irods/irods_docs/commit/ee4cf50841a4a0d8a242bd96ba1faf8839e15675

Perhaps there are other parts that need adjusting as well. It certainly could stand to be expanded a bit.

**Comment by korydraughn** [comment]
You're correct. If the documentation needs tweaking, we can always open new issues.

Closing.
