### ISSUE TITLE
Add documentation to troubleshooting section for 4.2.12, MySQL 8, and `DataObjInCollReCur`

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_docs#188]
See https://github.com/irods/irods/issues/6900#issuecomment-1437401987

**Comment by alanking** [comment]
We did it? 4-2-stable only? Or do we need to make a slightly modified version of this note in the docs for 4.3.1?

**Comment by korydraughn** [comment]
4-2-stable only. 4.3 gets a code change.
