### ISSUE TITLE
http://issuestats.com/ link should be removed for 4.1.x version of documentation (site has changed)

### ISSUE THREAD

**Issue by efflamlemaillet** [irods/irods_docs#31]
# Bug Report

Documentation 4.1.x
## What did you try to do?

browsing on irods documentation

## Observed behavior (including steps to reproduce, if applicable)

issuestats.com is now a poker blog (link is present on top of page https://docs.irods.org/4.1.12/ to https://docs.irods.org/4.1.1/ )

**Comment by trel** [comment]
ah, got it - thanks!

**Comment by trel** [comment]
I've removed the links.
