### ISSUE TITLE
Update rebalance queries for 4.2.X

### ISSUE THREAD

**Issue by bh9** [irods/irods_docs#65]
The rebalance queries still use resc_name, which is stale in 4.2.X
https://github.com/irods/irods_docs/blob/master/docs/plugins/composable_resources.md#rebalance
Could these queries be updated to serve the same purpose on 4.2.X?

**Comment by trel** [comment]
The resc_id-based rebalance queries are now dynamically derived, and cannot be saved like that ahead of time anymore.

I expect we'll need to remove those examples from the 4.2 documentation.

**Comment by trel** [comment]
We are looking into adding a dry-run option to the rebalance operation to get some totals, but that may not be viable as rebalance pages through the returned rows itself to get the work done.
